# Generated by Django 4.1.1 on 2022-10-12 01:50

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('news_url', models.URLField()),
                ('media', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=5, verbose_name=models.CharField(max_length=10))),
                ('key_words', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=8)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=8)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('first_img_url', models.URLField()),
                ('pub_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='user_basic_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=12, unique=True)),
                ('password', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='user_preference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=10)),
                ('num', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user_basic_info')),
            ],
        ),
        migrations.CreateModel(
            name='search_history',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=38)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user_basic_info')),
            ],
        ),
    ]
