# Generated by Django 4.1.1 on 2022-10-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbasicinfo',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
