# Generated by Django 4.1.1 on 2022-10-12 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_basic_info',
            table='user_basic_info',
        ),
    ]
