# Generated by Django 4.1.1 on 2022-10-26 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_userbasicinfo_tags'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='news',
            table='news',
        ),
        migrations.AlterModelTable(
            name='searchhistory',
            table='search_history',
        ),
        migrations.AlterModelTable(
            name='userbasicinfo',
            table='user_basic_info',
        ),
        migrations.AlterModelTable(
            name='userpreference',
            table='user_preference',
        ),
    ]
