# Generated by Django 4.1.1 on 2022-10-12 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_basic_info_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_basic_info',
            table=None,
        ),
    ]
