# Generated by Django 4.1.1 on 2022-10-26 11:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_userbasicinfo_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='first_img_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None),
        ),
    ]
