# Generated by Django 4.1.1 on 2022-10-26 15:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_news_table_alter_searchhistory_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeNews',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('news_url', models.URLField()),
                ('media', models.CharField(max_length=20)),
                ('category', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=5)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('first_img_url', models.TextField(blank=True)),
                ('pub_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'home_news',
            },
        ),
    ]
