# Generated by Django 4.1.1 on 2022-10-12 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_basic_info_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='news',
            table='news',
        ),
        migrations.AlterModelTable(
            name='search_history',
            table='search_history',
        ),
        migrations.AlterModelTable(
            name='user_basic_info',
            table='user_basic_info',
        ),
        migrations.AlterModelTable(
            name='user_preference',
            table='user_preference',
        ),
    ]
