# Generated by Django 4.1.1 on 2022-10-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_news_table_alter_search_history_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_basic_info',
            name='password',
            field=models.CharField(max_length=40),
        ),
    ]
