# Generated by Django 4.1.1 on 2022-10-31 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_homenews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homenews',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
