# Generated by Django 4.1.1 on 2022-11-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_homenews_category_alter_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbasicinfo',
            name='avatar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userbasicinfo',
            name='mail',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
