# Generated by Django 4.1.1 on 2022-10-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_search_history_searchhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbasicinfo',
            name='signature',
            field=models.CharField(default='sign', max_length=200),
            preserve_default=False,
        ),
    ]
