# Generated by Django 4.1.1 on 2022-11-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userbasicinfo_avatar_userbasicinfo_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbasicinfo',
            name='favorites',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
