# Generated by Django 4.1.1 on 2022-11-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_userbasicinfo_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbasicinfo',
            name='favorites',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
