# Generated by Django 4.1.1 on 2022-11-06 15:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_userbasicinfo_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbasicinfo',
            name='favorites',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, null=True), default=list, size=None),
        ),
    ]
