# Generated by Django 4.1.1 on 2022-11-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_userbasicinfo_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbasicinfo',
            name='favorites',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
