# Generated by Django 4.1.1 on 2022-11-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_userbasicinfo_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbasicinfo',
            name='readlater_list',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
