# Generated by Django 4.1.1 on 2022-11-08 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_userbasicinfo_readlater_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbasicinfo',
            old_name='readlater_list',
            new_name='readlist',
        ),
    ]
