# Generated by Django 4.1.1 on 2022-11-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_readlater_list_userbasicinfo_readlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbasicinfo',
            name='read_history',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
