# Generated by Django 4.1.1 on 2022-11-16 07:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_userbasicinfo_read_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbasicinfo',
            name='register_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbasicinfo',
            name='search_history',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
