# Generated by Django 4.1.1 on 2022-11-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_userbasicinfo_register_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalNews',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('data', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'db_table': 'local_news',
            },
        ),
    ]
