# Generated by Django 4.1.1 on 2022-11-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_localnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='localnews',
            name='ai_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='localnews',
            name='news_id',
            field=models.IntegerField(default=0),
        ),
    ]
