# Generated by Django 4.1.1 on 2022-11-19 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_localnews_cite_cound'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localnews',
            old_name='cite_cound',
            new_name='cite_count',
        ),
    ]
