# Generated by Django 4.1.1 on 2022-11-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_cite_cound_localnews_cite_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbasicinfo',
            name='tags',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
