# Generated by Django 4.1.1 on 2022-11-24 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_userbasicinfo_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeNews',
        ),
    ]
